const STORAGE_KEY = 'nordlof-leadgenerator-v1';
const STATUSES = {new:'Ny',qualified:'Kvalificerad',contacted:'Kontaktad',followup:'Följ upp',won:'Vunnen',lost:'Förlorad'};
const PROJECTS = [
  {keywords:['fastighet','bostad','brf','förvaltning'],name:'Fastighetsnavet',pitch:'en tydligare webbplats eller digital lösning för fastighetsinformation och kundärenden'},
  {keywords:['bygg','trädgård','mark','anläggning'],name:'Hansen Bygg & Grönt',pitch:'en snabb, lokal och säljande tjänstesida med offertförfrågan'},
  {keywords:['uthyrning','event','aktivitet','kalas','förening'],name:'Offroad Bumpis',pitch:'ett bokningsflöde med priser, lagerregler och tydliga kundvillkor'},
  {keywords:['säkerhet','standard','kvalitet','dokumentation'],name:'Safe Standard',pitch:'en strukturerad webbapp för dokumentation, rutiner och kvalitetssäkring'},
  {keywords:['reklam','marknadsföring','sociala medier','kampanj'],name:'Reklamapp',pitch:'ett enklare flöde för kampanjer, innehåll och uppföljning'},
  {keywords:['ai','automation','process','projekt'],name:'ProjectMind AI',pitch:'en AI-stödd lösning som minskar manuellt arbete och samlar arbetsflödet'},
  {keywords:['api','integration','backend','data'],name:'Mini API / FlowForge',pitch:'en stabil API- eller backendlösning som kopplar ihop befintliga system'}
];

const demoLeads = [
  {id:crypto.randomUUID(),company:'Malmö Markservice AB',industry:'Trädgård och mark',city:'Malmö',website:'',contactName:'',email:'info@example.se',need:'Saknar modern webbplats och tydligt offertformulär.',webQuality:25,hasContact:10,localFit:15,needStrength:30,status:'new',followup:'',notes:'',updatedAt:Date.now()},
  {id:crypto.randomUUID(),company:'Öresund Fastighetsservice',industry:'Fastighetsservice',city:'Lund',website:'https://example.se',contactName:'Anna',email:'anna@example.se',need:'Otydlig tjänstestruktur och inget digitalt felanmälningsflöde.',webQuality:15,hasContact:10,localFit:15,needStrength:30,status:'qualified',followup:'',notes:'Ring inte – skriftlig kontakt först.',updatedAt:Date.now()-1000},
  {id:crypto.randomUUID(),company:'Skåne Event & Aktivitet',industry:'Event och uthyrning',city:'Helsingborg',website:'https://example.com',contactName:'Johan',email:'johan@example.com',need:'Manuell bokning via mejl. Behöver enklare lager- och bokningssystem.',webQuality:5,hasContact:10,localFit:15,needStrength:30,status:'contacted',followup:'',notes:'',updatedAt:Date.now()-2000}
];

let leads = loadLeads();
let selectedId = null;
const $ = id => document.getElementById(id);
const refs = {rows:$('leadRows'),empty:$('emptyState'),search:$('searchInput'),status:$('statusFilter'),score:$('scoreFilter'),sort:$('sortSelect'),dialog:$('leadDialog'),form:$('leadForm')};

function loadLeads(){try{const data=JSON.parse(localStorage.getItem(STORAGE_KEY));return Array.isArray(data)?data:demoLeads}catch{return demoLeads}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(leads));render()}
function score(l){return Math.min(100,Number(l.webQuality||0)+Number(l.hasContact||0)+Number(l.localFit||0)+Number(l.needStrength||0)+(/https?:\/\//.test(l.website||'')?0:10))}
function temp(s){return s>=75?'hot':s>=50?'warm':'cold'}
function projectFor(l){const hay=`${l.industry} ${l.need}`.toLowerCase();return PROJECTS.find(p=>p.keywords.some(k=>hay.includes(k)))||{name:'Webbbuilder Studio',pitch:'en snabb, modern webbplats med tydligt erbjudande och enkel kontaktväg'}}
function filtered(){const q=refs.search.value.trim().toLowerCase();return leads.filter(l=>{const s=score(l);const text=`${l.company} ${l.industry} ${l.city} ${l.need}`.toLowerCase();const scoreOk=refs.score.value==='all'||temp(s)===refs.score.value;return (!q||text.includes(q))&&(refs.status.value==='all'||l.status===refs.status.value)&&scoreOk}).sort((a,b)=>refs.sort.value==='company-asc'?a.company.localeCompare(b.company,'sv'):refs.sort.value==='updated-desc'?b.updatedAt-a.updatedAt:score(b)-score(a))}
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function render(){const list=filtered();refs.rows.innerHTML=list.map(l=>{const s=score(l),p=projectFor(l);return `<tr data-id="${l.id}" class="${l.id===selectedId?'selected':''}"><td class="company"><strong>${escapeHtml(l.company)}</strong><small>${escapeHtml([l.industry,l.city].filter(Boolean).join(' · '))}</small></td><td>${escapeHtml(p.name)}</td><td><span class="score ${temp(s)}">${s}</span></td><td><span class="status">${STATUSES[l.status]||l.status}</span></td><td>${escapeHtml(l.followup||'Ej satt')}</td></tr>`}).join('');refs.empty.hidden=list.length>0;$('totalCount').textContent=leads.length;$('hotCount').textContent=leads.filter(l=>score(l)>=75).length;$('contactedCount').textContent=leads.filter(l=>['contacted','followup'].includes(l.status)).length;$('wonCount').textContent=leads.filter(l=>l.status==='won').length;refs.rows.querySelectorAll('tr').forEach(r=>r.addEventListener('click',()=>selectLead(r.dataset.id)));if(selectedId&&!leads.some(l=>l.id===selectedId)){selectedId=null;clearDetail()}}
function selectLead(id){selectedId=id;const l=leads.find(x=>x.id===id);if(!l)return;const p=projectFor(l);$('detailCompany').textContent=l.company;$('detailMeta').textContent=[l.industry,l.city].filter(Boolean).join(' · ')||'Ingen metadata';$('detailContent').hidden=false;$('detailScore').textContent=score(l);$('detailWebsite').innerHTML=l.website?`<a href="${escapeHtml(l.website)}" target="_blank" rel="noopener">${escapeHtml(l.website)}</a>`:'Saknas';$('detailContact').textContent=[l.contactName,l.email].filter(Boolean).join(' · ')||'Saknas';$('detailNeed').textContent=l.need||'Inte angivet';$('detailProject').textContent=`${p.name} – ${p.pitch}`;$('detailStatus').innerHTML=Object.entries(STATUSES).map(([v,n])=>`<option value="${v}" ${v===l.status?'selected':''}>${n}</option>`).join('');$('detailFollowup').value=l.followup||'';$('detailNotes').value=l.notes||'';$('messageOutput').value='';render()}
function clearDetail(){$('detailCompany').textContent='Välj ett företag';$('detailMeta').textContent='Klicka på en rad för att se detaljer och skapa kontaktutkast.';$('detailContent').hidden=true}
function updateSelected(patch){const i=leads.findIndex(l=>l.id===selectedId);if(i<0)return;leads[i]={...leads[i],...patch,updatedAt:Date.now()};save();selectLead(selectedId)}
function openDialog(){refs.form.reset();$('dialogTitle').textContent='Ny lead';refs.dialog.showModal()}
function formToLead(){const f=new FormData(refs.form);return {id:crypto.randomUUID(),company:f.get('company').trim(),industry:f.get('industry').trim(),city:f.get('city').trim(),website:f.get('website').trim(),contactName:f.get('contactName').trim(),email:f.get('email').trim(),need:f.get('need').trim(),webQuality:Number(f.get('webQuality')),hasContact:Number(f.get('hasContact')),localFit:Number(f.get('localFit')),needStrength:Number(f.get('needStrength')),status:'new',followup:'',notes:'',updatedAt:Date.now()}}
function generateMessage(){const l=leads.find(x=>x.id===selectedId);if(!l)return;const p=projectFor(l);const first=l.contactName?` ${l.contactName.split(' ')[0]}`:'';$('messageOutput').value=`Hej${first},\n\nJag tittade på ${l.company} och såg att ${l.need?l.need.charAt(0).toLowerCase()+l.need.slice(1):'det finns möjlighet att göra ert digitala erbjudande tydligare'}.\n\nJag driver Nordlöf Nordic i Malmö och bygger praktiska webbplatser och system för mindre företag. Ett upplägg som skulle kunna passa er är ${p.pitch}.\n\nJag kan ta fram ett första konkret förslag på struktur och lösning utan onödiga möten. Ni avgör därefter om ni vill gå vidare.\n\nÄr det relevant att jag skickar ett kort förslag?\n\nVänliga hälsningar\nErica Nordlöf\nNordlöf Nordic\nwebutvecklare.se`;}
function csvEscape(v){const s=String(v??'');return /[",\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s}
function exportCsv(){const keys=['company','industry','city','website','contactName','email','need','status','followup','notes'];const rows=[keys.join(','),...leads.map(l=>keys.map(k=>csvEscape(l[k])).join(','))];const blob=new Blob(['\ufeff'+rows.join('\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`leads-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)}
function parseCsv(text){const rows=[];let row=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&quoted&&n==='"'){cell+='"';i++}else if(c==='"'){quoted=!quoted}else if(c===','&&!quoted){row.push(cell);cell=''}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&n==='\n')i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell=''}else cell+=c}row.push(cell);if(row.some(Boolean))rows.push(row);return rows}
function importCsv(file){const reader=new FileReader();reader.onload=()=>{const rows=parseCsv(reader.result);if(rows.length<2)return alert('CSV-filen saknar datarader.');const headers=rows[0].map(h=>h.trim());const imported=rows.slice(1).map(cols=>Object.fromEntries(headers.map((h,i)=>[h,cols[i]||'']))).filter(x=>x.company).map(x=>({...x,id:crypto.randomUUID(),webQuality:Number(x.webQuality||0),hasContact:Number(x.hasContact||0),localFit:Number(x.localFit||0),needStrength:Number(x.needStrength||0),status:x.status&&STATUSES[x.status]?x.status:'new',updatedAt:Date.now()}));leads=[...imported,...leads];save();alert(`${imported.length} leads importerades.`)};reader.readAsText(file,'utf-8')}

['searchInput','statusFilter','scoreFilter','sortSelect'].forEach(id=>$(id).addEventListener(id==='searchInput'?'input':'change',render));$('addLeadBtn').addEventListener('click',openDialog);$('saveLeadBtn').addEventListener('click',e=>{e.preventDefault();if(!refs.form.reportValidity())return;const l=formToLead();leads.unshift(l);save();refs.dialog.close();selectLead(l.id)});$('detailStatus').addEventListener('change',e=>updateSelected({status:e.target.value}));$('detailFollowup').addEventListener('change',e=>updateSelected({followup:e.target.value}));$('detailNotes').addEventListener('change',e=>updateSelected({notes:e.target.value}));$('generateMessageBtn').addEventListener('click',generateMessage);$('copyMessageBtn').addEventListener('click',async()=>{await navigator.clipboard.writeText($('messageOutput').value);$('copyMessageBtn').textContent='Kopierat';setTimeout(()=>$('copyMessageBtn').textContent='Kopiera',1200)});$('deleteLeadBtn').addEventListener('click',()=>{if(!confirm('Ta bort denna lead?'))return;leads=leads.filter(l=>l.id!==selectedId);selectedId=null;save();clearDetail()});$('exportBtn').addEventListener('click',exportCsv);$('csvInput').addEventListener('change',e=>{if(e.target.files[0])importCsv(e.target.files[0]);e.target.value=''});$('clearDemoBtn').addEventListener('click',()=>{if(confirm('Rensa alla leads och börja om?')){leads=[];selectedId=null;save();clearDetail()}});render();
